name: Hub Desc. Update on Tag

on:
  push:
    tags:
      - '*'

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v2
    -
      name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: ${{ github.repository }}
        short-description: ${{ github.event.repository.description }}
